import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { verifyAdminRequest } from "@/lib/server/auth";
import { adminDb, adminStorage } from "@/lib/server/firebase-admin";
import { writeAudit } from "@/lib/server/audit";

const MAX_BYTES = 12 * 1024 * 1024;
const types = new Map([["image/jpeg","jpg"],["image/png","png"],["image/webp","webp"],["image/avif","avif"]]);
function validSignature(type:string,bytes:Uint8Array){if(type==="image/jpeg")return bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;if(type==="image/png")return bytes.slice(0,8).every((value,index)=>value===[137,80,78,71,13,10,26,10][index]);if(type==="image/webp")return new TextDecoder().decode(bytes.slice(0,4))==="RIFF"&&new TextDecoder().decode(bytes.slice(8,12))==="WEBP";if(type==="image/avif")return new TextDecoder().decode(bytes.slice(4,12)).includes("ftyp");return false}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const actor=await verifyAdminRequest("content");if(!actor)return NextResponse.json({ok:false},{status:403});const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)return NextResponse.json({ok:false},{status:403});const{id}=await params;if(!/^[\w-]{1,128}$/.test(id))return NextResponse.json({ok:false},{status:404});const album=adminDb.collection("gallery_albums").doc(id);if(!(await album.get()).exists)return NextResponse.json({ok:false},{status:404});const form=await request.formData();const upload=form.get("image");if(!(upload instanceof File))return NextResponse.json({ok:false,message:"Select an image."},{status:400});const extension=types.get(upload.type);if(!extension||upload.size>MAX_BYTES)return NextResponse.json({ok:false,message:"Upload JPEG, PNG, WebP, or AVIF images up to 12 MB."},{status:400});const buffer=Buffer.from(await upload.arrayBuffer());if(!validSignature(upload.type,buffer))return NextResponse.json({ok:false,message:"The file contents do not match the declared image type."},{status:400});const imageId=randomUUID();const storagePath=`gallery/albums/${id}/${imageId}.${extension}`;try{const file=adminStorage.bucket().file(storagePath);await file.save(buffer,{resumable:false,contentType:upload.type,metadata:{cacheControl:"public,max-age=31536000,immutable"}});const url=`https://firebasestorage.googleapis.com/v0/b/${file.bucket.name}/o/${encodeURIComponent(storagePath)}?alt=media`;await writeAudit(actor.uid,"gallery.image.uploaded","gallery",id,{imageId,storagePath});return NextResponse.json({ok:true,image:{id:imageId,url,storagePath,alt:"",caption:"",order:0}},{status:201})}catch{return NextResponse.json({ok:false,message:"Firebase Storage is unavailable."},{status:503})}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const actor=await verifyAdminRequest("content");if(!actor)return NextResponse.json({ok:false},{status:403});const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)return NextResponse.json({ok:false},{status:403});const{id}=await params;if(!/^[\w-]{1,128}$/.test(id))return NextResponse.json({ok:false},{status:404});const body=await request.json().catch(()=>null) as {imageId?:unknown;storagePath?:unknown}|null;const imageId=typeof body?.imageId==="string"?body.imageId:"";const storagePath=typeof body?.storagePath==="string"?body.storagePath:"";if(!/^[\w-]{1,128}$/.test(imageId)||!storagePath.startsWith(`gallery/albums/${id}/${imageId}.`))return NextResponse.json({ok:false},{status:400});const ref=adminDb.collection("gallery_albums").doc(id);if(!(await ref.get()).exists)return NextResponse.json({ok:false},{status:404});await adminStorage.bucket().file(storagePath).delete({ignoreNotFound:true});await writeAudit(actor.uid,"gallery.image.removed","gallery",id,{imageId,storagePath});return NextResponse.json({ok:true})}
