import { describe, expect, it } from "vitest";
import { ageGroupFor, calculateSmsAudience, contactMatchesAudience, contactMatchesDirectoryFilters, contactSchema, deriveAge, isSmsEligibleContact, prepareContact } from "@/lib/contacts";

describe("contact management", () => {
  it("derives safe age groups", () => { expect(deriveAge("2000-08-14", new Date("2026-08-14T12:00:00Z"))).toBe(26); expect(ageGroupFor(17)).toBe("under_18"); expect(ageGroupFor(25)).toBe("25_34"); expect(ageGroupFor(66)).toBe("65_plus"); });
  it("normalizes Ghana phones without fabricating demographics", () => { const parsed=contactSchema.parse({phone:"024 123 4567",source:"staff"}); const contact=prepareContact(parsed); expect(contact.normalizedPhone).toBe("+233241234567"); expect(contact.gender).toBe(""); expect(contact.age).toBeNull(); });
  it("matches female health screening contacts aged 25-44", () => { const contact={status:"active",doNotContact:false,smsOptIn:true,phone:"+233241234567",gender:"female",ageGroup:"25_34",source:"health_screening",sources:["health_screening"],facility:"Kutunse Screening - Aug 2026",tags:["outreach"]}; expect(contactMatchesAudience(contact,{gender:"female",ageGroups:["25_34","35_44"],source:"health_screening",facility:"Kutunse Screening - Aug 2026",tags:["outreach"],smsConsent:true,hasPhone:true})).toBe(true); });
  it("matches consented contacts aged 55+", () => { expect(contactMatchesAudience({status:"active",doNotContact:false,smsOptIn:true,phone:"+233241234567",ageGroup:"65_plus"},{ageGroups:["55_64","65_plus"],smsConsent:true,hasPhone:true})).toBe(true); });
  it("always excludes archived, opted-out and do-not-contact records", () => { const f={smsConsent:true,hasPhone:true}; expect(contactMatchesAudience({status:"archived",smsOptIn:true,phone:"+233241234567"},f)).toBe(false); expect(contactMatchesAudience({status:"active",smsOptIn:false,phone:"+233241234567"},f)).toBe(false); expect(contactMatchesAudience({status:"active",smsOptIn:true,doNotContact:true,phone:"+233241234567"},f)).toBe(false); });
  it("excludes recently contacted recipients", () => { const contact={status:"active",smsOptIn:true,doNotContact:false,phone:"+233241234567",lastContactedAt:"2026-08-10"}; expect(contactMatchesAudience(contact,{smsConsent:true,hasPhone:true,excludeContactedSince:"2026-08-01"},new Date("2026-08-14"))).toBe(false); });
  it("applies all directory filters consistently", () => { const contact={fullName:"Ama Mensah",phone:"+233241234567",email:"ama@example.com",source:"health_screening",sources:["health_screening"],gender:"female",ageGroup:"25_34",facility:"Kutunse Screening",tags:["outreach"],smsOptIn:true,status:"active"}; expect(contactMatchesDirectoryFilters(contact,{q:"ama",source:"health_screening",gender:"female",ageGroup:"25_34",facility:"kutunse",tag:"out",consent:"sms",status:"active"})).toBe(true); expect(contactMatchesDirectoryFilters(contact,{gender:"male"})).toBe(false); });
  it("separates SMS eligibility from ordinary matching", () => { expect(isSmsEligibleContact({status:"active",smsOptIn:true,doNotContact:false,phone:"0241234567"})).toBe(true); expect(isSmsEligibleContact({status:"active",smsOptIn:false,phone:"0241234567"})).toBe(false); expect(isSmsEligibleContact({status:"archived",smsOptIn:true,phone:"0241234567"})).toBe(false); });
  it("explains every audience exclusion without inflating queued recipients", () => { const contacts=[{id:"a",status:"active",smsOptIn:true,phone:"0241234567",gender:"female",ageGroup:"25_34"},{id:"b",status:"active",smsOptIn:false,phone:"0201234567",gender:"female",ageGroup:"25_34"},{id:"c",status:"active",smsOptIn:true,phone:"invalid",gender:"female",ageGroup:"25_34"},{id:"d",status:"active",smsOptIn:true,doNotContact:true,phone:"0501234567",gender:"female",ageGroup:"25_34"},{id:"e",status:"active",smsOptIn:true,phone:"0541234567",gender:"female",ageGroup:"25_34"},{id:"f",status:"active",smsOptIn:true,phone:"0241234567",gender:"female",ageGroup:"25_34"},{id:"g",status:"archived",smsOptIn:true,phone:"0591234567",gender:"female",ageGroup:"25_34"}]; expect(calculateSmsAudience(contacts,{source:"all_contacts",gender:"female",ageGroups:["25_34"]},new Set(["e"]))).toEqual({totalContacts:7,filterMatches:7,active:6,validMobile:5,smsConsent:4,eligible:1,noConsent:1,invalidPhone:1,optedOut:1,doNotContact:1,duplicates:1,otherExclusions:1}); });
  it.each(["under_18","18_24","25_34","35_44","45_54","55_64","65_plus"])("filters the %s age group", ageGroup => { const contacts=[{id:"a",status:"active",smsOptIn:true,phone:"0241234567",gender:"female",ageGroup},{id:"b",status:"active",smsOptIn:true,phone:"0201234567",gender:"male",ageGroup:""}]; expect(calculateSmsAudience(contacts,{source:"all_contacts",ageGroups:[ageGroup]}).filterMatches).toBe(1); });
});
