"use client";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import type { GalleryAlbum } from "@/lib/gallery";

export function GalleryExplorer({ albums }: { albums: GalleryAlbum[] }) {
  const categories = ["All", ...Array.from(new Set(albums.map(album => album.category)))];
  const [category, setCategory] = useState("All");
  const visible = category === "All" ? albums : albums.filter(album => album.category === category);
  return <><div className="flex gap-2 overflow-x-auto pb-2" role="group" aria-label="Filter gallery albums">{categories.map(item => <button key={item} type="button" aria-pressed={category === item} onClick={() => setCategory(item)} className={`min-h-11 shrink-0 rounded-full border px-5 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-deep ${category === item ? "border-purple-deep bg-purple-deep text-white" : "border-border-default bg-white text-text-body hover:border-purple-deep"}`}>{item}</button>)}</div>{visible.length ? <div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{visible.map((album, index) => { const cover = album.images.find(image => image.id === album.coverImageId) ?? album.images[0]; return <article key={album.id} className={`group overflow-hidden rounded-3xl border border-border-default bg-white shadow-sm ${album.featured && index === 0 ? "md:col-span-2" : ""}`}><Link href={`/gallery/${album.slug}`} className="block focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-deep"><div className={`relative overflow-hidden bg-bg-soft ${album.featured && index === 0 ? "aspect-[16/9]" : "aspect-[4/3]"}`}>{cover ? <Image src={cover.url} alt={cover.alt} fill sizes={album.featured && index === 0 ? "(max-width: 768px) 100vw, 66vw" : "(max-width: 768px) 100vw, 33vw"} className="object-cover transition-transform duration-500 motion-reduce:transition-none group-hover:scale-[1.02]" unoptimized={cover.url.startsWith("/")} preload={album.featured && index === 0} /> : null}</div><div className="p-6"><span className="text-xs font-semibold uppercase tracking-wider text-pink-accent">{album.category}</span><h2 className="mt-2 text-xl font-semibold text-text-dark">{album.title}</h2>{album.shortDescription ? <p className="mt-2 text-sm leading-relaxed text-text-body">{album.shortDescription}</p> : null}<div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-sm text-text-muted"><span>{album.images.length} {album.images.length === 1 ? "photo" : "photos"}</span><span className="font-semibold text-purple-deep">View Gallery →</span></div></div></Link></article>})}</div> : <div className="mt-8 rounded-3xl border border-dashed border-border-default bg-bg-soft p-12 text-center text-text-body">No published albums are available in this category.</div>}</>;
}
