import Link from "next/link";
import { requireAdmin } from "@/lib/server/auth";
import { adminDb } from "@/lib/server/firebase-admin";
import { submissionKinds } from "@/lib/types/submissions";

function dateFrom(value: unknown) {
  if (value && typeof value === "object" && "toDate" in value && typeof value.toDate === "function") return value.toDate();
  return null;
}

export default async function Dashboard(){await requireAdmin();const now=new Date();const today=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()));const week=new Date(today);week.setUTCDate(week.getUTCDate()-6);const followUpHours=Math.max(1,Number(process.env.FOLLOW_UP_HOURS??48));const overdue=new Date(now.getTime()-followUpHours*3600000);const cards=await Promise.all(Object.entries(submissionKinds).map(async([kind,c])=>{const snapshot=await adminDb.collection(c.collection).select("status","createdAt").get();let count=0;let todayCount=0;let weekCount=0;let overdueCount=0;for(const doc of snapshot.docs){const data=doc.data();const status=String(data.status??"");const createdAt=dateFrom(data.createdAt);if(status==="new")count++;if(createdAt&&createdAt>=today)todayCount++;if(createdAt&&createdAt>=week)weekCount++;if(createdAt&&createdAt<=overdue&&(status==="new"||status==="in_review"))overdueCount++;}return{kind,label:c.label,count,today:todayCount,week:weekCount,overdue:overdueCount}}));return <section><p className="text-sm font-semibold text-pink-accent">OPERATIONAL OVERVIEW</p><h1 className="text-3xl font-semibold text-purple-deep">Dashboard</h1><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cards.map(card=><Link key={card.kind} href={`/admin/${card.kind}`} className="rounded-2xl bg-white p-6 shadow-sm"><p className="text-sm text-text-muted">{card.label}</p><p className="mt-2 text-4xl font-semibold text-purple-deep">{card.count}<span className="ml-2 text-xs font-medium text-text-muted">new</span></p><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><span className="rounded-lg bg-bg-soft p-2">{card.today}<br/>today</span><span className="rounded-lg bg-bg-soft p-2">{card.week}<br/>7 days</span><span className="rounded-lg bg-bg-soft p-2">{card.overdue}<br/>follow-up</span></div></Link>)}</div><p className="mt-5 text-sm text-text-muted">Follow-up means new or in-review for more than {followUpHours} hours. Hospital approval of this threshold is required.</p></section>}
