"use client";
import { useState } from "react";
import { campaignSources, defaultFeedbackMessage } from "@/lib/feedback-campaigns";

type Campaign={code:string;name:string;source:string;message:string;status:string;recipientCount:number;queuedCount:number;mockedCount:number;deliveredCount:number;failedCount:number;responseCount:number};
async function post(url:string,body:unknown){const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.message||"The request could not be completed.");return data}
export function FeedbackCampaignManager({initialCampaigns,canSend}:{initialCampaigns:Campaign[];canSend:boolean}){
 const [items,setItems]=useState(initialCampaigns),[name,setName]=useState(""),[source,setSource]=useState<(typeof campaignSources)[number]>("health_screening"),[message,setMessage]=useState(defaultFeedbackMessage),[values,setValues]=useState<Record<string,string>>({}),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 async function run(fn:()=>Promise<void>,success:string){setBusy(true);setNotice("");try{await fn();setNotice(success)}catch(e){setNotice(e instanceof Error?e.message:"Request failed.")}finally{setBusy(false)}}
 function update(code:string,change:Partial<Campaign>){setItems(old=>old.map(x=>x.code===code?{...x,...change}:x))}
 return <div className="mt-6 space-y-6"><section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-semibold">Create campaign</h2><div className="mt-4 grid gap-4 lg:grid-cols-2"><label className="font-semibold">Name<input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label><label className="font-semibold">Source<select value={source} onChange={e=>setSource(e.target.value as typeof source)} className="mt-2 w-full rounded-xl border p-3">{campaignSources.map(x=><option key={x}>{x}</option>)}</select></label><label className="font-semibold lg:col-span-2">Controlled SMS template<textarea value={message} onChange={e=>setMessage(e.target.value)} rows={4} className="mt-2 w-full rounded-xl border p-3"/><small className="block text-text-muted">Keep [SURVEY LINK]. Never add clinical information.</small></label></div><button disabled={busy} onClick={()=>run(async()=>{const d=await post("/api/admin/feedback/campaigns",{name,source,message});setItems(old=>[{code:d.code,name,source,message,status:"draft",recipientCount:0,queuedCount:0,mockedCount:0,deliveredCount:0,failedCount:0,responseCount:0},...old]);setName("")},"Draft campaign created.")} className="mt-4 rounded-xl bg-purple-deep px-5 py-3 font-semibold text-white">Create draft</button></section>
 {notice&&<p role="status" className="rounded-xl bg-amber-50 p-4">{notice}</p>}
 <section className="space-y-4"><h2 className="text-xl font-semibold">Campaigns</h2>{!items.length&&<p className="rounded-2xl border bg-white p-5">No campaigns yet.</p>}{items.map(c=><article key={c.code} className="rounded-2xl border bg-white p-5"><h3 className="text-lg font-semibold">{c.name}</h3><p className="text-sm text-text-muted">{c.source} · {c.status} · {c.code}</p><div className="mt-4 grid grid-cols-3 gap-2 sm:grid-cols-6">{[["Recipients",c.recipientCount],["Queued",c.queuedCount],["Mocked",c.mockedCount],["Delivered",c.deliveredCount],["Failed",c.failedCount],["Responses",c.responseCount]].map(([l,v])=><div key={String(l)} className="rounded-xl bg-bg-soft p-2 text-center"><strong className="block">{v}</strong><small>{l}</small></div>)}</div><p className="mt-2 text-sm">Response rate: {c.recipientCount?Math.round(c.responseCount/c.recipientCount*100):0}% {c.recipientCount<10&&"(small sample)"}</p><p className="mt-4 rounded-xl bg-bg-soft p-3 text-sm">{c.message.replace("[SURVEY LINK]",`/feedback?campaign=${c.code}&source=sms`)}</p>
 {(["draft","ready"].includes(c.status))&&<div className="mt-4"><label className="font-semibold">Consented Ghana phone numbers<textarea value={values[`recipients-${c.code}`]||""} onChange={e=>setValues({...values,[`recipients-${c.code}`]:e.target.value})} rows={4} className="mt-2 w-full rounded-xl border p-3" placeholder="One per line or comma separated"/></label><button disabled={busy} onClick={()=>run(async()=>{const d=await post(`/api/admin/feedback/campaigns/${c.code}/recipients`,{recipients:values[`recipients-${c.code}`]||""});update(c.code,{status:"ready",recipientCount:c.recipientCount+d.added,queuedCount:c.queuedCount+d.added-d.optedOut})},"Recipients imported; duplicates, invalid numbers and opt-outs were skipped.")} className="mt-2 rounded-xl border px-4 py-2 font-semibold">Import and review</button></div>}
 {canSend&&c.queuedCount>0&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><strong>Mock batch only</strong><p className="text-sm">No SMS will be sent. Type SEND {c.queuedCount} to simulate the queued batch.</p><div className="mt-2 flex flex-wrap gap-2"><input value={values[`confirm-${c.code}`]||""} onChange={e=>setValues({...values,[`confirm-${c.code}`]:e.target.value})} className="rounded-xl border p-2"/><button disabled={busy} onClick={()=>run(async()=>{const d=await post(`/api/admin/feedback/campaigns/${c.code}/send`,{action:"batch",confirmation:values[`confirm-${c.code}`]||""});update(c.code,{status:"mock_complete",mockedCount:c.mockedCount+d.processed,queuedCount:c.queuedCount-d.processed})},"Mock batch completed; no real SMS was sent.")} className="rounded-xl bg-purple-deep px-4 py-2 text-white">Run mock batch</button></div><div className="mt-2 flex flex-wrap gap-2"><input placeholder="Test Ghana number" value={values[`test-${c.code}`]||""} onChange={e=>setValues({...values,[`test-${c.code}`]:e.target.value})} className="rounded-xl border p-2"/><button disabled={busy} onClick={()=>run(async()=>{await post(`/api/admin/feedback/campaigns/${c.code}/send`,{action:"test",testPhone:values[`test-${c.code}`],confirmation:"SEND TEST"})},"Mock test completed; no real SMS was sent.")} className="rounded-xl border px-4 py-2">Mock test</button></div></div>}</article>)}</section></div>
}
